FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Use $PORT variable for Railway
CMD ["gunicorn", "main:app", "--bind", "0.0.0.0:$PORT"]